name: build

on:
  push:
    branches: [ "main" ]
  pull_request:


jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3

    - name: Set reusable strings
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Compile
      run: >
        gcc lscommand.c -o lsc
